# Generated by Django 4.1.2 on 2022-11-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_brand_category_brand_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item',
        ),
    ]
