# Generated by Django 4.1.2 on 2022-11-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productphoto',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
        migrations.AddField(
            model_name='productphoto',
            name='category',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
