# Generated by Django 4.1.3 on 2022-12-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productphoto_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productphoto',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
