# Generated by Django 4.1.3 on 2022-12-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_orderitem_rename_datetime_order_date_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customuser',
            new_name='customer',
        ),
    ]
