# Generated by Django 4.1.3 on 2022-12-18 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_customuser_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xususiyatlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vazni', models.CharField(blank=True, max_length=100, null=True)),
                ('razmeri', models.CharField(blank=True, max_length=100, null=True)),
                ('os_versiyasi', models.CharField(blank=True, max_length=200, null=True)),
                ('wi_fi_standarti', models.CharField(blank=True, max_length=100, null=True)),
                ('SIM_karta_turi', models.CharField(blank=True, max_length=200, null=True)),
                ('aloqa_standarti', models.CharField(blank=True, max_length=120, null=True)),
                ('kafolat_muddati', models.CharField(blank=True, max_length=30, null=True)),
                ('old_kamera_olchamlari', models.CharField(blank=True, max_length=50, null=True)),
                ('eshitish_vositasi', models.CharField(blank=True, max_length=50, null=True)),
                ('ornatilgan_xotira', models.CharField(blank=True, max_length=50, null=True)),
                ('operativ_xotira', models.CharField(blank=True, max_length=50, null=True)),
                ('protsessor', models.CharField(blank=True, max_length=50, null=True)),
                ('korpus_materiali', models.CharField(blank=True, max_length=100, null=True)),
                ('registratsiya', models.CharField(blank=True, max_length=50, null=True)),
                ('max_vedio_olchami', models.CharField(blank=True, max_length=50, null=True)),
                ('orqa_kamera_soni', models.CharField(blank=True, max_length=50, null=True)),
                ('xotira_kartasi_uyasi', models.CharField(blank=True, max_length=50, null=True)),
                ('simsiz_interfeyslar', models.CharField(blank=True, max_length=50, null=True)),
                ('batareya_quvvati', models.CharField(blank=True, max_length=100, null=True)),
                ('asosiy_kamera', models.CharField(blank=True, max_length=50, null=True)),
                ('vedio_tezligi', models.CharField(blank=True, max_length=50, null=True)),
                ('max_kadr_tezligi', models.CharField(blank=True, max_length=50, null=True)),
                ('prosessor_yadrolari_soni', models.CharField(blank=True, max_length=50, null=True)),
                ('fullhd_vedio_tezligi', models.CharField(blank=True, max_length=60, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
    ]
